Repository avrdudes/avrdude, pull requests merged in 2022-11, with the labels that each got.

#1164 Fix Type 2 HV UPDI
  src/jtag3.c
  src/libavrdude.h
Labels: bug

#1182 Rewrite authors/copyrights
  AUTHORS
  src/main.c
Labels: documentation

#1185 Add a workaround for issue #1173
  src/term.c
Labels: bug

#1181 Add fallback for EM_AVR
  build.sh
  src/fileio.c
  src/ser_posix.c
  src/term.c
Labels: enhancement

#1147 Add xplainedpro_pdi programmer
  src/avrdude.conf.in
Labels: enhancement

#1171 Provide Urclock programmer
  src/CMakeLists.txt
  src/Makefile.am
  src/avr.c
  src/avrcache.c
  src/avrdude.1
  src/avrdude.conf.in
  src/avrintel.c
  src/avrintel.h
  src/config.c
  src/developer_opts.c
  src/doc/avrdude.texi
  src/libavrdude.h
  src/main.c
  src/pgm.c
  src/pgm_type.c
  src/ser_posix.c
  src/ser_win32.c
  src/term.c
  src/update.c
  src/urclock.c
  src/urclock.h
  src/urclock_private.h
Labels: enhancement

#1172 Fix #1167 removing the initialize call following the CMD_CHIP_ERASE_ISP command
  src/stk500v2.c
Labels: bug

#1174 Ensure default_programmer from config files is used
  src/main.c
Labels: bug

#1175 Make terminal write's automatic number width less surprising
  src/avrdude.1
  src/doc/avrdude.texi
  src/term.c
Labels: enhancement

#1184 Print HAVE_LIBREADLINE status
  CMakeLists.txt
  src/configure.ac
Labels: enhancement

#1187 Revert PR #1156
  .github/workflows/build.yml
  build.sh
Labels: bug

#1196 Disable GNU Readline for MSVC build
  .github/workflows/build.yml
Labels: bug

#1188 Pad pages with input file contents before avr_write()
  src/avr.c
  src/avrcache.c
  src/libavrdude.h
  src/update.c
  src/urclock.c
Labels: bug

#1189 Deprecate mosi/miso in favour of sdo/sdi
  src/avrdude.1
  src/avrdude.conf.in
  src/avrftdi.c
  src/avrftdi_tpi.c
  src/avrintel.c
  src/avrintel.h
  src/bitbang.c
  src/buspirate.c
  src/config_gram.y
  src/doc/avrdude.texi
  src/ft245r.c
  src/lexer.l
  src/libavrdude.h
  src/linuxgpio.c
  src/linuxspi.c
  src/pgm.c
  src/pickit2.c
  src/pindefs.c
  src/stk500.c
  src/stk500v2.c
  src/stk500v2_private.h
  src/usbtiny.c
Labels: enhancement

#1190 Provide bootloader-hash tool
  src/urclock.c
  tools/bootloader-hash
Labels: enhancement

#1191 Fix parameters for JTAGICE mkII and devices with bootloaders
  src/avrdude.conf.in
  src/config.c
  src/developer_opts.c
  src/doc/avrdude.texi
  src/jtagmkII.c
  src/lexer.l
  src/libavrdude.h
Labels: bug

#1194 Fix shell exit value when chip erase is delayed to next flash write
  src/avr.c
  src/libavrdude.h
  src/main.c
Labels: bug

#1198 Tie up loose ends for urclock programmer
  src/avr.c
  src/avrcache.c
  src/avrdude.1
  src/avrdude.conf.in
  src/avrpart.c
  src/config.c
  src/config_gram.y
  src/developer_opts.c
  src/doc/avrdude.texi
  src/jtagmkII.c
  src/lexer.l
  src/libavrdude.h
  src/main.c
  src/serialupdi.c
  src/stk500v2.c
  src/updi_nvm.c
  src/urclock.c
Labels: enhancement

#1199 Fix userrow size and page_size for ATtiny3216 and ATtiny3217
  src/avrdude.conf.in
Labels: bug
