Repository avrdudes/avrdude, pull requests merged in 2022-10, with the labels that each got.

#1101 Fix avr109 extended address
  src/butterfly.c
Labels: bug

#1102 Add support for Flip 2 reset on exit
  src/avrdude.1
  src/doc/avrdude.texi
  src/flip2.c
Labels: enhancement

#1105 Support for Power Debugger analog readings in terminal mode
  src/jtag3.c
  src/jtag3.h
  src/jtag3_private.h
  src/stk500v2.c
  src/term.c
Labels: enhancement

#1106 Provide cached byte-wise read/write API
  src/CMakeLists.txt
  src/Makefile.am
  src/avr.c
  src/avrcache.c
  src/avrdude.1
  src/doc/avrdude.texi
  src/libavrdude.h
  src/pgm.c
  src/term.c
Labels: enhancement

#1108 AVR109: support for prodsig read and usersig read/write
  src/butterfly.c
Labels: enhancement

#1109 Add missing AVR variants the original JTAG ICE supports
  src/avrdude.conf.in
Labels: enhancement

#1113 In terminal only offer commands a programmer actually supports
  src/avrcache.c
  src/avrdude.1
  src/doc/avrdude.texi
  src/libavrdude.h
  src/pgm.c
  src/term.c
Labels: enhancement

#1119 Fix pointer truncation for Windows x64
  src/term.c
Labels: bug

#1112 Fix jtag3_page_erase for targets with UPDI
  src/jtag3.c
Labels: enhancement

#1115 Fix writing of last word on DWORD TPI parts
  src/avr.c
  src/avrdude.conf.in
  src/config.c
  src/developer_opts.c
  src/doc/avrdude.texi
  src/lexer.l
  src/libavrdude.h
Labels: bug

#1121 Use byte-wise read/write when page size is 1 in terminal cache
  src/avrcache.c
Labels: bug

#1122 Suppress Teensy USB communication error message on reboot
  src/teensy.c
Labels: bug

#1125 Fix UPDI erase when target is locked
  src/avrdude.conf.in
  src/main.c
  src/serialupdi.c
Labels: bug

#1126 Review and overhaul AVRDUDE's messaging system
  src/arduino.c
  src/avr.c
  src/avr910.c
  src/avrcache.c
  src/avrdude.h
  src/avrftdi.c
  src/avrftdi_private.h
  src/avrpart.c
  src/bitbang.c
  src/buspirate.c
  src/butterfly.c
  src/config.c
  src/config_gram.y
  src/developer_opts.c
  src/dfu.c
  src/fileio.c
  src/flip1.c
  src/flip2.c
  src/ft245r.c
  src/jtag3.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/linux_ppdev.h
  src/linuxgpio.c
  src/linuxspi.c
  src/main.c
  src/micronucleus.c
  src/par.c
  src/pgm.c
  src/pickit2.c
  src/pindefs.c
  src/ppi.c
  src/ppiwin.c
  src/ser_avrdoper.c
  src/ser_posix.c
  src/ser_win32.c
  src/serbb_posix.c
  src/serbb_win32.c
  src/serialupdi.c
  src/stk500.c
  src/stk500generic.c
  src/stk500v2.c
  src/teensy.c
  src/term.c
  src/update.c
  src/updi_link.c
  src/updi_nvm.c
  src/updi_readwrite.c
  src/usb_hidapi.c
  src/usb_libusb.c
  src/usbasp.c
  src/usbtiny.c
  src/wiring.c
  src/xbee.c
Labels: enhancement

#1131 Look for ~/.config/avrdude/config configuration file
  src/avrdude.1
  src/avrdude.conf.in
  src/avrdude.h
  src/doc/avrdude.texi
  src/main.c
Labels: enhancement

#1132 Revamp terminal output (progress bar, callback and stdout/stderr)
  build.sh
  src/avr.c
  src/avrcache.c
  src/avrdude.h
  src/avrpart.c
  src/flip2.c
  src/jtag3.c
  src/jtag3.h
  src/jtagmkI.c
  src/jtagmkII.c
  src/libavrdude.h
  src/main.c
  src/pgm.c
  src/stk500.c
  src/stk500v2.c
  src/term.c
  src/term.h
  src/update.c
Labels: enhancement

#1138 Detect PICkit4 and SNAP in PIC mode
  src/avrdude.conf.in
  src/jtag3.c
  src/usb_hidapi.c
  src/usbdevs.h
Labels: enhancement

#1139 Mention -B in the error message
  src/avrdude.1
  src/doc/avrdude.texi
  src/main.c
Labels: enhancement

#1140 Support optiboot, optiboot_dx and optiboot_x bootloaders for -c arduino
  src/stk500.c
Labels: bug, enhancement

#1141 Always use paged access for programmers that serve bootloaders
  src/avr.c
Labels: bug

#1146 Add libreadline-dev for Linux github action build
  .github/workflows/build.yml
Labels: enhancement

#1148 Add readline for MSYS2 mingw32/mingw64 build
  .github/workflows/build.yml
Labels: enhancement

#1142 STK600 supports programming using PDI
  src/avrdude.conf.in
Labels: enhancement

#1156 Readline macos
  .github/workflows/build.yml
  build.sh
Labels: enhancement

#1151 Implementation of SerialUPDI page erase operation
  src/serialupdi.c
Labels: enhancement
