Repository avrdudes/avrdude, pull requests merged in 2022-12, with the labels that each got.

#1205 Added TPI support for Microchip tools
  src/avrcache.c
  src/avrdude.conf.in
  src/jtag3.c
  src/jtag3.h
  src/jtag3_private.h
  src/pgm_type.c
  src/stk500v2.c
  src/stk500v2_private.h
Labels: enhancement

#1206 Fix reading of .elf files
  src/fileio.c
Labels: bug

#1207 Consider libreadline/libedit only in interactive mode
  src/term.c
Labels: bug, enhancement

#1208 Add partial urclock support for parts with bootloaders in low flash
  src/urclock.c
Labels: enhancement

#1209 Terminal read improvements
  src/term.c
Labels: enhancement

#1216 Print meaningful error when a too slow ISP clock is detected
  src/main.c
  src/stk500v2.c
  src/stk500v2_private.h
Labels: enhancement

#1220 Remove extraneous avrdude> prompt at end of terminal session
  src/term.c
Labels: bug

#1223 Read programmer serial number from libusb or hidusb
  src/jtag3.c
  src/jtag3.h
  src/libavrdude.h
  src/stk500v2.c
  src/usb_hidapi.c
  src/usb_libusb.c
Labels: enhancement

#1226 Hint at -xeepromrw option in EEPROM error messages
  src/CMakeLists.txt
  src/Makefile.am
  src/avrdude.1
  src/doc/avrdude.texi
  src/urclock.c
  src/urclock_hash.h
Labels: enhancement

#1233 #1052 Add JTAG support for PICkit4 and Snap.
  src/avrdude.1
  src/avrdude.conf.in
  src/doc/avrdude.texi
  src/jtag3.c
Labels: enhancement

#1234 Mention developer options in documentation and Usage()
  src/avrdude.1
  src/doc/avrdude.texi
  src/main.c
Labels: documentation

#1239 Temporarily disable brew update in macOS github action
  .github/workflows/build.yml
Labels: enhancement

#1241 Update build.sh for NetBSD
  build.sh
Labels: enhancement

#1237 Print expected signature when the one read by the programmer doesn't match the expected one
  src/main.c
Labels: enhancement

#1242 Add FT2232H support for Windows, Tigard programmer
  CMakeLists.txt
  src/avrdude.conf.in
Labels: bug, enhancement

#1246 Modify recv timeouts to accommodate urclock sync with ftdi
  src/urclock.c
Labels: bug

#1243 CMake updates
  .github/workflows/build.yml
  CMakeLists.txt
  CMakeSettings.json
  src/CMakeLists.txt
Labels: bug, enhancement

#1247 Silence conf path detection debug output
  src/main.c
Labels: enhancement

#1248 Make WIN32 implementation of ser_recv() fail on time-out
  src/ser_win32.c
Labels: bug

#1251 Guard urclock_getsync() against initial spurious input
  src/avrdude.1
  src/doc/avrdude.texi
  src/urclock.c
Labels: bug
