Repository avrdudes/avrdude, pull requests merged in 2022-06, with the labels that each got.

#979 Dragon JTAG fix
  src/jtagmkII.c
Labels: bug

#993 adding support for all Linux baud rates v.2
  src/ser_posix.c
Labels: enhancement

#996 Replace internal knowledge in jtag3.c by a public API
  src/avr.c
  src/jtag3.c
  src/jtag3_private.h
  src/libavrdude.h
  src/main.c
Labels: enhancement

#1013 JTAG3 UPDI EEPROM fix
  src/jtag3.c
Labels: bug

#943 Fix Issue #942: Treat x bits in .conf SPI commands as 0
  NEWS
  src/avrpart.c
Labels: enhancement, question
