Repository avrdudes/avrdude, pull requests merged in 2022-08, with the labels that each got.

#1016 CMakeLists.txt: fix build without C++
  CMakeLists.txt
  src/CMakeLists.txt
Labels: enhancement

#1030 Provide file format I: Intel HEX with comments that ignores checksum errors
  src/avrdude.1
  src/doc/avrdude.texi
  src/fileio.c
  src/libavrdude.h
  src/update.c
Labels: enhancement

#1031 Apply jtagmki patch provided in #443
  src/jtagmkI.c
Labels: bug

#1033 Ignore `-s` flag as safemode is no longer supported
  src/avrdude.1
  src/doc/avrdude.texi
  src/main.c
Labels: bug

#1040 Developer options to describe parts and extend avrdude.conf syntax
  src/CMakeLists.txt
  src/Makefile.am
  src/avrdude.conf.in
  src/avrpart.c
  src/config_gram.y
  src/developer_opts.c
  src/developer_opts.h
  src/developer_opts_private.h
  src/lexer.l
  src/libavrdude.h
  src/main.c
  src/pgm.c
Labels: enhancement

#1048 Add `jtagmkii_updi` programmer option
  src/avrdude.conf.in
  src/jtagmkII.c
  src/jtagmkII.h
  src/pgm_type.c
Labels: bug

#1053 Enable stdin verification and display correct number of bytes written/verified
  src/avr.c
  src/config_gram.y
  src/developer_opts.c
  src/libavrdude.h
  src/main.c
  src/update.c
Labels: bug, enhancement

#1042 Handle invalid -U file format specifiers for input
  src/avrdude.1
  src/doc/avrdude.texi
  src/fileio.c
  src/update.c
Labels: documentation

#1056 Implement a dry run for -U updates before opening the programmer
  src/fileio.c
  src/libavrdude.h
  src/main.c
  src/msvc/msvc_compat.h
  src/update.c
Labels: enhancement

#1059 Implement -c <wildcard>/dev_options for printing programmer entries of avrdude.conf
  src/avr.c
  src/avrftdi.c
  src/avrpart.c
  src/config.c
  src/config.h
  src/config_gram.y
  src/developer_opts.c
  src/developer_opts.h
  src/developer_opts_private.h
  src/ft245r.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/lexer.l
  src/libavrdude.h
  src/main.c
  src/pgm.c
  src/pgm_type.c
  src/pickit2.c
  src/pindefs.c
  src/ser_avrdoper.c
  src/ser_win32.c
  src/stk500v2.c
  src/term.c
  src/update.c
  src/usbasp.c
Labels: enhancement

#1063 man-page: Fix logfile short option
  src/CMakeLists.txt
  src/avrdude.1
Labels: documentation

#1083 Make avr910 programmer initialize() less verbose
  src/avr910.c
Labels: enhancement

#1074 Correct flash paged write for avrftdi.c
  src/avrftdi.c
Labels: bug

#1086 Rewrite avrdude.conf.in with developer options
  src/avrdude.conf.in
  src/developer_opts.c
  src/pindefs.c
Labels: bug, enhancement

#1091 Add new components in `avrdude.conf.in`
  src/CMakeLists.txt
  src/Makefile.am
  src/avr.c
  src/avrdude.conf.in
  src/avrftdi.c
  src/avrintel.c
  src/avrintel.h
  src/avrpart.c
  src/bitbang.c
  src/config.c
  src/config.h
  src/config_gram.y
  src/developer_opts.c
  src/doc/avrdude.texi
  src/fileio.c
  src/flip1.c
  src/flip2.c
  src/ft245r.c
  src/jtag3.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/lexer.l
  src/libavrdude.h
  src/linuxspi.c
  src/main.c
  src/stk500v2.c
  src/usbasp.c
  src/usbtiny.c
Labels: enhancement
