Repository avrdudes/avrdude, pull requests merged in 2023-06, with the labels that each got.

#1373 Implement -T cmd to mix terminal commands with -U commands
  src/CMakeLists.txt
  src/Makefile.am
  src/avrdude.1
  src/doc/avrdude.texi
  src/fileio.c
  src/libavrdude.h
  src/main.c
  src/strutil.c
  src/term.c
  src/term.h
  src/update.c
Labels: enhancement

#1375 Prevent terminal write error in r/o region when memory unchanged
  src/avrcache.c
Labels: bug

#1376 Remove pgm->page_erase() function when unable to erase page
  src/avr.c
  src/avrcache.c
  src/jtag3.c
  src/jtagmkII.c
  src/stk500v2.c
Labels: bug

#1378 Write fuse only when terminal config needs value to change
  src/term.c
Labels: enhancement

#1383 Provide programmer arduino_as_isp
  src/avrdude.conf.in
  src/stk500.c
Labels: bug, enhancement

#1385 Provide debug messages for the dryrun programmer
  src/dryrun.c
Labels: enhancement

#1392 Rewrite fileio functions to cater for a list of memory segments
  src/fileio.c
  src/libavrdude.h
  src/strutil.c
Labels: bug, enhancement

#1393 Add more documentation for urclock programmer
  src/avrdude.conf.in
  src/main.c
  src/urclock.c
Labels: documentation

#1394 Add more info for the arduino programmer
  src/avrdude.conf.in
Labels: documentation

#1395 Add more info for the dryrun programmer
  src/avrdude.conf.in
Labels: documentation

#1396 Provide terminal save command
  src/avrdude.1
  src/doc/avrdude.texi
  src/fileio.c
  src/libavrdude.h
  src/term.c
Labels: enhancement

#1397 Provide subshell command `!` in the terminal
  src/avrdude.1
  src/avrdude.conf.in
  src/config.c
  src/config_gram.y
  src/developer_opts.c
  src/doc/avrdude.texi
  src/lexer.l
  src/libavrdude.h
  src/main.c
  src/term.c
Labels: enhancement

#1386 Fix stk500v2.c's write_byte() for old parts
  src/avrdude.conf.in
  src/stk500v2.c
Labels: bug

#1399 Document terminal comments
  src/avrdude.1
  src/doc/avrdude.texi
  src/term.c
Labels: documentation

#1400 Expand authorship of documentation
  src/avrdude.1
  src/doc/avrdude.texi
Labels: documentation

#1401 Fix memory leak in avrcache.c
  src/avrcache.c
Labels: bug

#1402 Run -t interactive terminals when it is their turn wrt -t/-T/-U options
  src/avrdude.1
  src/doc/avrdude.texi
  src/main.c
  src/update.c
Labels: enhancement

#1403 Mute missing USB device warning for lower verbosity levels
  src/usb_hidapi.c
Labels: enhancement

#1404 Implement bytewise cache for usersig
  src/avr.c
  src/avrcache.c
  src/avrdude.1
  src/doc/avrdude.texi
  src/libavrdude.h
  src/pgm.c
Labels: enhancement

#1405 Relax checks before executing the -T/-U operations
  src/update.c
Labels: enhancement

#1406 Define usersig memory for ATmega*RF[AR]* parts
  src/avrdude.conf.in
  src/developer_opts.c
Labels: bug

#1411 Increase timeout for emulated butterfly chip erase
  src/butterfly.c
  src/urclock.c
Labels: bug

#1415 Update reference to AT90S4433 datasheet
  src/avrdude.conf.in
  src/doc/avrdude.texi
  src/libavrdude.h
Labels: documentation

#1416 Update alf programmer info and URL
  src/avrdude.conf.in
Labels: documentation

#1417 Update URLs for 89isp programmer
  src/avrdude.conf.in
Labels: documentation

#1418 Update ft2232h programmer info and URLs
  src/avrdude.conf.in
Labels: documentation

#1419 Update butterfly_mk info
  src/avrdude.conf.in
Labels: documentation

#1420 Remove outdated web URLs for O-Link
  src/avrdude.conf.in
Labels: documentation

#1421 Update URLs for the ttl232r programmer
  src/avrdude.conf.in
Labels: documentation

#1422 Update usbasp programmer info
  src/avrdude.conf.in
Labels: documentation

#1423 Remove comment and URL for arduino-ft232r programmer
  src/avrdude.conf.in
Labels: documentation

#1424 Enable -c programmers to access -c string
  src/avr910.c
  src/avrdude.h
  src/buspirate.c
  src/config_gram.y
  src/developer_opts.c
  src/dryrun.c
  src/jtag3.c
  src/jtagmkII.c
  src/libavrdude.h
  src/linuxspi.c
  src/main.c
  src/micronucleus.c
  src/pgm.c
  src/pickit2.c
  src/serialupdi.c
  src/stk500.c
  src/stk500v2.c
  src/teensy.c
  src/term.c
  src/urclock.c
  src/usbasp.c
  src/wiring.c
  src/xbee.c
Labels: enhancement

#1429 Add scratchmonkey programmers
  src/avrdude.conf.in
  src/stk500v2.c
Labels: enhancement

#1430 Use pgm->id list for different names of the same AVR programmer
  src/avrdude.conf.in
Labels: enhancement

#1438 Write empty flash memory to file in correct format
  src/fileio.c
Labels: bug

#1439 Provide terminal include command
  src/avrdude.1
  src/doc/avrdude.texi
  src/term.c
Labels: enhancement

#1450 Update info on bsd programmer
  src/avr.c
  src/avrdude.1
  src/avrdude.conf.in
  src/avrpart.c
  src/bitbang.c
  src/bitbang.h
  src/config.c
  src/config.h
  src/config_gram.y
  src/fileio.c
  src/jtagmkI.h
  src/jtagmkII.c
  src/jtagmkII.h
  src/lexer.l
  src/lists.c
  src/main.c
  src/par.c
  src/par.h
  src/pgm.c
  src/pgm_type.c
  src/pickit2.c
  src/pindefs.c
  src/ppi.c
  src/ppi.h
  src/serbb.h
  src/serbb_posix.c
  src/stk500.c
  src/stk500.h
  src/stk500v2.c
  src/stk500v2.h
  src/term.c
  src/update.c
  supporting-docs/avrprog.pdf
Labels: documentation

#1425 Add jtag2updi -xrtsdtr extended parameter
  src/avrdude.1
  src/doc/avrdude.texi
  src/jtagmkII.c
  src/jtagmkII_private.h
  src/serialupdi.c
Labels: enhancement
