Repository avrdudes/avrdude, pull requests merged in 2023-10, with the labels that each got.

#1512 libserialport github action
  .github/workflows/build.yml
Labels: enhancement

#1513 Add GNU readline to mingw github action
  .github/workflows/build.yml
Labels: enhancement

#1516 Update build.yml to revert PR #1513
  .github/workflows/build.yml
Labels: bug

#1507 Support for serial port "touch" functionality using libserialport
  src/avrdude.1
  src/doc/avrdude.texi
  src/libavrdude.h
  src/main.c
  src/ser_avrdoper.c
  src/ser_posix.c
  src/ser_win32.c
  src/serialadapter.c
  src/usb_hidapi.c
  src/usb_libusb.c
  src/xbee.c
Labels: enhancement

#1510 Read sigrow for ATmega32[48]PB using ISP
  src/avr.c
  src/avrdude.1
  src/avrdude.conf.in
  src/avrpart.c
  src/config_gram.y
  src/doc/avrdude.texi
Labels: enhancement

#1511 Adapt stk500 readback values for usbtiny.c
  src/usbtiny.c
Labels: bug

#1517 Add LED support for ScratchMonkey programmer
  src/stk500v2.c
  src/stk500v2_private.h
Labels: enhancement

#1518 Review and update prodsig memories for U/PDI parts
  src/avrdude.conf.in
Labels: enhancement

#1519 Add id as comment to avrdude.conf definitions
  src/avrdude.conf.in
  src/developer_opts.c
Labels: enhancement

#1520 Enable prodsig read for stk500v2 based programmers
  src/stk500v2.c
Labels: enhancement

#1521 Enable prodsig read for avrftdi_jtag type programmers
  src/avrftdi.c
Labels: enhancement

#1522 Model prodsig for -c dryrun
  src/dryrun.c
Labels: enhancement

#1523 Fix tempsense size, AVR-EB memory offsets and avrdude.conf memory order
  src/avr.c
  src/avrdude.conf.in
  src/jtag3.c
Labels: bug, enhancement

#1524 Enable prodsig read for jtagmkI programmers
  src/jtagmkI.c
Labels: enhancement

#1525 Enable prodsig read for jtagmkII programmers
  src/jtagmkII.c
Labels: enhancement

#1526 Enable prodsig read for jtag3 programmers
  src/jtag3.c
Labels: enhancement

#1528 Review LED support
  src/CMakeLists.txt
  src/Makefile.am
  src/avr.c
  src/avrcache.c
  src/avrdude.1
  src/avrftdi.c
  src/avrpart.c
  src/bitbang.c
  src/buspirate.c
  src/butterfly.c
  src/doc/avrdude.texi
  src/ft245r.c
  src/leds.c
  src/libavrdude.h
  src/main.c
  src/pgm.c
  src/pickit2.c
  src/stk500.c
  src/stk500v2.c
  src/term.c
  src/update.c
Labels: bug, enhancement

#1531 Fix candidate for issues with NVM v3 controller
  src/serialupdi.c
Labels: bug

#1533 Add bootloader hashes from the Sanguino Arduino core repo
  src/urclock.c
Labels: enhancement

#1539 To support MinGW cross compiler
  src/CMakeLists.txt
Labels: enhancement

#1542 Add Avrdude build version into avrdude.conf
  src/CMakeLists.txt
  src/avrdude.conf.in
  src/configure.ac
Labels: enhancement

#1547 Add avrdude_conf_version to grammar
  src/avrdude.conf.in
  src/config.c
  src/config_gram.y
  src/configure.ac
  src/developer_opts.c
  src/doc/avrdude.texi
  src/lexer.l
  src/libavrdude.h
  src/main.c
Labels: bug, enhancement
