Repository avrdudes/avrdude, pull requests merged in 2023-01, with the labels that each got.

#1231 Change definition of NO_PIN to (PIN_MAX + 1U)
  src/avr.c
  src/avrftdi.c
  src/bitbang.c
  src/buspirate.c
  src/config_gram.y
  src/libavrdude.h
  src/linuxgpio.c
  src/linuxspi.c
  src/par.c
  src/pgm.c
  src/pindefs.c
  src/serbb_posix.c
  src/serbb_win32.c
Labels: bug

#1256 Fix partial matches for locate_mem() and do_cmd()
  src/avrpart.c
  src/term.c
Labels: bug

#1255 Add a "q" command to the terminal
  src/term.c
Labels: enhancement

#1260 Clean up avrdude.conf.in fixing a couple of bugs
  src/avrdude.conf.in
  src/avrintel.c
  src/avrintel.h
  src/config_gram.y
  src/developer_opts.c
  src/lexer.l
Labels: bug

#1264 Add readline library replacement for MSVC
  CMakeLists.txt
  src/CMakeLists.txt
  src/msvc/readline.cpp
  src/msvc/readline/history.h
  src/msvc/readline/readline.h
  src/term.c
Labels: enhancement

#1265 Ensure full words are loaded, low-byte first, for ISP programming
  src/avr.c
Labels: bug

#1266 Silence page erase in cache code
  src/avrcache.c
Labels: bug

#1269 Update to latest MSVC fork of hidapi to include bug fixes
  CMakeLists.txt
Labels: bug

#1268 Update GitHub actions
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  CMakeSettings.json
Labels: enhancement

#1279 Update configure.ac for MinGW build
  src/configure.ac
Labels: bug

#1280 Update configure.ac to reflect HAVE_READLINE statue
  src/configure.ac
Labels: bug

#1272 Correct memory mode, delay and readback for classic parts
  src/avrdude.conf.in
  src/developer_opts.c
Labels: bug

#1273 Only send write flash cmd to STK500v2 programmers if page not empty
  src/stk500v2.c
Labels: bug

#1276 Document fix for avrftdi bit number should start with 0
  src/doc/avrdude.texi
Labels: documentation

#1277 Silence gcc compiler warnings
  src/CMakeLists.txt
  src/avr910.c
  src/butterfly.c
  src/configure.ac
  src/dfu.c
  src/flip1.c
  src/flip2.c
  src/ft245r.c
  src/jtag3.c
  src/jtagmkI.c
  src/lists.c
  src/micronucleus.c
  src/pgm_type.c
  src/pickit2.c
  src/pindefs.c
  src/ser_avrdoper.c
  src/serialupdi.c
  src/update.c
  src/usb_hidapi.c
  src/usbasp.c
  src/usbtiny.c
Labels: bug, enhancement

#1282 Reduce complexity of grammar
  src/config.c
  src/config.h
  src/config_gram.y
  src/developer_opts_private.h
  src/lexer.l
Labels: enhancement

#1297 Revert PR https://github.com/avrdudes/avrdude/pull/1280
  src/configure.ac
Labels: bug
