Repository avrdudes/avrdude, pull requests merged in 2023-05, with the labels that each got.

#1342 Add options processing
  build.sh
Labels: enhancement

#1357 Progressively shrink metadata for -c urclock
  src/avrdude.1
  src/doc/avrdude.texi
  src/fileio.c
  src/urclock.c
Labels: enhancement

#1358 Extend <data> notion to files in terminal write
  src/avrdude.1
  src/config.c
  src/config.h
  src/config_gram.y
  src/developer_opts.c
  src/doc/avrdude.texi
  src/fileio.c
  src/lexer.l
  src/libavrdude.h
  src/linuxspi.c
  src/main.c
  src/strutil.c
  src/term.c
  src/update.c
  src/urclock.c
Labels: enhancement

#1360 Add fuse0 to ATxmega128A4U/64A4U/32A4U/16A4U
  src/avrdude.conf.in
Labels: enhancement

#1363 Adds configuration for Kanda's AVRISP-U programmer.
  src/avrdude.conf.in
Labels: enhancement

#1364 Add more Avrdude CLI usage examples
  src/avrdude.conf.in
  src/doc/avrdude.texi
Labels: documentation

#1365 Provide terminal config command to set fuses and lock bits
  src/avrdude.1
  src/avrdude.conf.in
  src/avrintel.c
  src/avrintel.h
  src/config.c
  src/doc/avrdude.texi
  src/dryrun.c
  src/fileio.c
  src/libavrdude.h
  src/strutil.c
  src/term.c
  src/urclock.c
Labels: enhancement

#1372 Initialise unused bits of classic-part fuses with factory defaults
  src/avr.c
  src/avrdude.conf.in
  src/avrintel.c
  src/avrintel.h
  src/avrpart.c
  src/config.c
  src/config_gram.y
  src/developer_opts.c
  src/doc/avrdude.texi
  src/dryrun.c
  src/flip1.c
  src/flip2.c
  src/jtag3.c
  src/lexer.l
  src/libavrdude.h
  src/main.c
  src/term.c
Labels: bug
