Repository avrdudes/avrdude, pull requests merged in 2023-11, with the labels that each got.

#1538 Introduce memory types in lieu of string comparisons with memory names
  src/avr.c
  src/avr910.c
  src/avrcache.c
  src/avrdude.1
  src/avrdude.conf.in
  src/avrftdi.c
  src/avrintel.h
  src/avrpart.c
  src/bitbang.c
  src/buspirate.c
  src/butterfly.c
  src/ch341a.c
  src/config.c
  src/config_gram.y
  src/developer_opts.c
  src/doc/avrdude.texi
  src/dryrun.c
  src/fileio.c
  src/flip1.c
  src/flip2.c
  src/ft245r.c
  src/jtag3.c
  src/jtag3_private.h
  src/jtagmkI.c
  src/jtagmkII.c
  src/jtagmkII_private.h
  src/jtagmkI_private.h
  src/libavrdude.h
  src/main.c
  src/micronucleus.c
  src/pickit2.c
  src/ser_posix.c
  src/ser_win32.c
  src/serialupdi.c
  src/stk500.c
  src/stk500v2.c
  src/strutil.c
  src/teensy.c
  src/term.c
  src/update.c
  src/urclock.c
  src/usb_hidapi.c
  src/usb_libusb.c
  src/usbasp.c
  src/usbtiny.c
Labels: enhancement

#1540 Add Arduino avrdude_packing github action for git man
  .github/workflows/arduino_packing.yml
Labels: enhancement

#1543 Change execution position of "silicon revision" check of "serialupdi.c"
  src/serialupdi.c
Labels: enhancement

#1549 Issue#1546 Allow UPDI_SIB of AVR_EB in serialupdi
  src/serialupdi.c
Labels: enhancement

#1554 Review write_byte() functions
  src/avr.c
  src/avrftdi.c
  src/butterfly.c
  src/developer_opts.c
  src/flip1.c
  src/flip2.c
  src/jtag3.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/leds.c
  src/serialupdi.c
  src/stk500v2.c
  src/usbasp.c
Labels: enhancement

#1556 Remove paged eeprom property from ATtiny43U
  src/avrdude.conf.in
  src/doc/avrdude.texi
Labels: bug

#1557 Test programmers for prog_modes and type
  src/main.c
Labels: bug

#1555 Provide option -N for do not load personal config file
  src/avrdude.1
  src/doc/avrdude.texi
  src/main.c
Labels: enhancement

#1563 Always print error if part and programmer doesn't have a common programming interface
  src/main.c
Labels: bug

#1564 Print warning when avrdude and avrdude.conf versions doesn't match
  src/main.c
Labels: enhancement

#1566 Support for STK500 v1 and v2 devices with STK500_XTAL != 7372800
  src/avrdude.1
  src/doc/avrdude.texi
  src/stk500.c
  src/stk500.h
  src/stk500v2.c
  src/stk500v2_private.h
Labels: enhancement

#1568 Update `part` cmd
  src/avrdude.1
  src/avrftdi.c
  src/avrpart.c
  src/doc/avrdude.texi
  src/ft245r.c
  src/jtag3.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/libavrdude.h
  src/linuxgpio.c
  src/main.c
  src/pgm.c
  src/ser_posix.c
  src/ser_win32.c
  src/stk500.c
  src/stk500v2.c
  src/term.c
  src/usb_libusb.c
Labels: enhancement

#1571 Add memory sram and remove memory data
  src/avr.c
  src/avrdude.conf.in
  src/avrpart.c
  src/fileio.c
  src/jtag3.c
  src/jtag3_private.h
  src/jtagmkII.c
  src/jtagmkII_private.h
  src/libavrdude.h
  src/main.c
  src/stk500v2.c
Labels: enhancement

#1576 Add GNU readline to mingw github action
  .github/workflows/build.yml
  src/CMakeLists.txt
Labels: enhancement

#1577 Provide and use libavrude functions to access part config values
  src/avrcache.c
  src/avrpart.c
  src/config.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/libavrdude.h
  src/term.c
Labels: bug, enhancement
