Repository avrdudes/avrdude, pull requests merged in 2023-12, with the labels that each got.

#1574 new functions (#1570): get_vtarget, get_varef, get_fosc, get_sck_period
  src/jtagmkI.c
  src/libavrdude.h
  src/pgm.c
  src/stk500.c
  src/stk500v2.c
  src/term.c
Labels: enhancement

#1580 Provide terminal `regfile` command
  src/avrdude.1
  src/avrintel.c
  src/avrintel.h
  src/avrpart.c
  src/doc/avrdude.texi
  src/dryrun.c
  src/jtag3.c
  src/libavrdude.h
  src/strutil.c
  src/term.c
Labels: enhancement

#1581 Ignore port settings when using -c dryrun
  src/main.c
Labels: bug

#1583 Add more PL2303 compatible USB PIDs
  src/avrdude.conf.in
Labels: enhancement

#1586 faster build.sh script with option -j
  build.sh
Labels: enhancement

#1587 Terminal mode improvements
  src/jtag3.c
  src/jtag3.h
  src/jtagmkII.c
  src/main.c
  src/stk500v2.c
  src/term.c
Labels: enhancement

#1588 Issue #973: Differentiate multiple USB programmers of the same VID/PI…
  src/doc/avrdude.texi
  src/usbasp.c
Labels: enhancement

#1590 Provide user config value "default_baudrate" (acc. discussion #1589)
  src/avrdude.1
  src/avrdude.conf.in
  src/config.c
  src/config_gram.y
  src/developer_opts.c
  src/doc/avrdude.texi
  src/lexer.l
  src/libavrdude.h
  src/main.c
Labels: enhancement

#1592 Update avrdude.texi: more index entries; header uppercase; correct @xref
  src/doc/avrdude.texi
Labels: documentation

#1593 Use Levenshtein distance to suggest a valid programmer name if -c is invalid
  src/avrdude.conf.in
  src/libavrdude.h
  src/main.c
  src/pgm.c
  src/strutil.c
  src/term.c
Labels: enhancement
