Repository avrdudes/avrdude, pull requests merged in 2024-05, with the labels that each got.

#1800 Silence compiler warnings
  src/dfu.c
  src/flip2.c
  src/updi_link.c
Labels: bug

#1802 Fix 7 typos in 4 files
  src/config.c
  src/fileio.c
  src/jtagmkII_private.h
  src/term.c
Labels: misc

#1803 Put static variables into context structure
  src/arduino.c
  src/avr.c
  src/avrcache.c
  src/avrdude.h
  src/avrftdi.c
  src/avrftdi_tpi.c
  src/avrpart.c
  src/bitbang.c
  src/config.c
  src/config_gram.y
  src/confwin.c
  src/developer_opts.c
  src/dfu.c
  src/fileio.c
  src/flip1.c
  src/libavrdude.h
  src/main.c
  src/pgm.c
  src/pindefs.c
  src/ppi.c
  src/ser_avrdoper.c
  src/ser_posix.c
  src/ser_win32.c
  src/serbb_posix.c
  src/serbb_win32.c
  src/serialadapter.c
  src/strutil.c
  src/term.c
  src/update.c
  src/urclock.c
  src/usb_libusb.c
Labels: enhancement

#1806 Differentiate cause when programmer isn't found
  src/avrftdi.c
  src/main.c
Labels: misc

#1808 Prepare for next urboot version
  src/urclock.c
  src/urclock_private.h
Labels: enhancement

#1810 Warn when programmer failes to define `prog_modes`
  src/config_gram.y
  src/lexer.l
  src/libavrdude.h
Labels: enhancement
