Repository avrdudes/avrdude, pull requests merged in 2024-01, with the labels that each got.

#1596 Use -xmode to switch PICkit4 and SNAP application modes
  src/avrdude.1
  src/doc/avrdude.texi
  src/jtag3.c
  src/jtag3.h
  src/jtag3_private.h
  src/stk500v2.c
  src/stk500v2_private.h
  src/usb_libusb.c
  src/usbdevs.h
Labels: enhancement

#1601 Support AVR64DU28 and AVR64DU32
  src/avrdude.conf.in
  src/avrintel.c
  src/avrintel.h
  src/lexer.l
Labels: enhancement

#1602 Force STK500 EEPROM paged r/w for bootloaders
  src/stk500.c
  src/urclock.c
Labels: bug

#1603 jtagmkII_updi_term_keep_alive
  src/jtagmkII.c
Labels: enhancement

#1604 Arduino Nano Every EEPROM writing
  src/jtagmkII.c
Labels: bug

#1605 Look for matching prog_modes in `locate_part_by_signature()`
  src/avrpart.c
  src/libavrdude.h
  src/main.c
Labels: enhancement

#1608 Harden AVRDUDE against pre-C99 libraries
  src/fileio.c
  src/main.c
  src/serbb_win32.c
  src/term.c
Labels: enhancement

#1612 Update build.yml to add MSYS2 ucrt64, clang32 and clang64 build
  .github/workflows/build.yml
Labels: enhancement

#1615 Update the GPL version 2 text
  COPYING
Labels: misc

#1618 Remove artificial 1Mhz limit on jtag3/atmelice/etc ISP bitclock
  src/stk500v2.c
Labels: enhancement

#1625 Detect dynamic readline and serialport libraries for avrdude USE_STATIC_LIBS builds
  CMakeLists.txt
Labels: bug

#1629 Fix typo from PR #1568
  src/linuxgpio.c
Labels: bug

#1631 Update `part` table in avrdude.texi
  src/doc/avrdude.texi
Labels: documentation

#1627 Multiple updates to SerialUPDI protocol based on discussion 1609 and issues 1621, 1622 and 1623.
  src/CMakeLists.txt
  src/Makefile.am
  src/serialupdi.c
  src/updi_constants.h
  src/updi_nvm.c
  src/updi_nvm_v0.c
  src/updi_nvm_v0.h
  src/updi_nvm_v2.c
  src/updi_nvm_v2.h
  src/updi_nvm_v3.c
  src/updi_nvm_v3.h
  src/updi_nvm_v4.c
  src/updi_nvm_v4.h
  src/updi_nvm_v5.c
  src/updi_nvm_v5.h
  src/updi_state.h
Labels: bug

#1634 Fix upload of one-byte files to flash
  src/avr.c
Labels: bug

#1640 Add CH343 USB to serial adapter
  src/avrdude.conf.in
Labels: enhancement

#1641 Add dryboot programmer
  src/avrdude.conf.in
  src/dryrun.c
Labels: enhancement

#1642 Provide terminal command `factory reset`
  src/avrdude.1
  src/avrdude.conf.in
  src/config.c
  src/developer_opts.c
  src/doc/avrdude.texi
  src/lexer.l
  src/libavrdude.h
  src/term.c
Labels: enhancement

#1646 Add tools/test-avrdude to Linux x86_64 github action
  .github/workflows/build.yml
Labels: enhancement

#1647 Add a fixed delay for AVR Dragon and Arduino Nano Every on port close
  src/avrdude.conf.in
  src/jtagmkII.c
Labels: enhancement

#1650 Update test-avrdude script
  tools/test-avrdude
Labels: bug
