Repository avrdudes/avrdude, pull requests merged in 2024-06, with the labels that each got.

#1801 Add serprog programmer
  src/CMakeLists.txt
  src/Makefile.am
  src/avrdude.1
  src/avrdude.conf.in
  src/doc/avrdude.texi
  src/pgm_type.c
  src/serprog.c
  src/serprog.h
Labels: enhancement

#1814 Remove EEPROM from ATtiny11 avrdude.conf entry
  src/avrdude.conf.in
Labels: bug

#1815 Guard serial_number access in usbhid_open() to avoid segfault
  src/usb_hidapi.c
Labels: bug

#1816 Allow selection of program modes for developer options
  src/developer_opts.c
  src/main.c
Labels: enhancement

#1818 Downgrade out-of-range file input errors to warnings on -F
  src/fileio.c
  src/term.c
Labels: enhancement

#1819 Update AUTHORS list
  AUTHORS
  src/jtag3.c
  src/jtag3.h
  src/jtag3_private.h
  src/stk500.c
  src/usb_libusb.c
Labels: documentation

#1820 Extend elf format for bootrow
  src/fileio.c
Labels: enhancement

#1822 Return -1 on write error
  src/avr.c
Labels: bug
