Repository avrdudes/avrdude, pull requests merged in 2024-08, with the labels that each got.

#1849 Update look and feel
  src/avr.c
  src/avr910.c
  src/avrdude.conf.in
  src/avrdude.h
  src/avrftdi.c
  src/avrftdi_tpi.c
  src/avrpart.c
  src/bitbang.c
  src/buspirate.c
  src/butterfly.c
  src/config.c
  src/developer_opts.c
  src/dfu.c
  src/dryrun.c
  src/fileio.c
  src/flip1.c
  src/flip2.c
  src/ft245r.c
  src/jtag3.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/libavrdude.h
  src/linuxgpio.c
  src/main.c
  src/micronucleus.c
  src/pgm.c
  src/pickit2.c
  src/pindefs.c
  src/ser_avrdoper.c
  src/ser_posix.c
  src/ser_win32.c
  src/serbb_posix.c
  src/serbb_win32.c
  src/serialadapter.c
  src/serialupdi.c
  src/stk500.c
  src/stk500generic.c
  src/stk500v2.c
  src/strutil.c
  src/teensy.c
  src/term.c
  src/update.c
  src/updi_link.c
  src/updi_nvm_v0.c
  src/updi_nvm_v3.c
  src/updi_nvm_v5.c
  src/urclock.c
  src/usb_hidapi.c
  src/usb_libusb.c
  src/usbasp.c
  src/usbtiny.c
  src/xbee.c
Labels: enhancement

#1853 Add missing documentation from #1844
  src/avrdude.1
  src/doc/avrdude.texi
Labels: documentation

#1855 Add more WCH USB to serial chips
  src/avrdude.conf.in
Labels: enhancement

#1856 cmake: LIB_NCURSES also accept pdcurses
  CMakeLists.txt
Labels: enhancement

#1859 Fix byte writes to TPI lockbits for jpag3.c
  src/jtag3.c
Labels: bug

#1862 Refine auto-erase strategy
  src/avrdude.1
  src/doc/avrdude.texi
  src/main.c
  src/term.c
Labels: bug

#1637 Use correct file locations in the documentation
  src/avrdude.1
Labels: documentation

#1695 Improve autotools build (part 2/n)
  .github/workflows/build.yml
  src/Makefile.am
  src/build-helpers/versioninfo.m4
  src/build-helpers/versioninfo.sh
  src/configure.ac
Labels: enhancement

#1857 doc: Stop building and installing .ps and .dvi
  src/avrdude.spec.in
  src/doc/CMakeLists.txt
  src/doc/Makefile.am
Labels: documentation

#1865 Provide current avrdude.pdf documentation in repo root
  README.md
  avrdude.pdf
Labels: documentation

#1867 Provide dev option `-c \*/u` that shows udev rules
  src/avrdude.conf.in
  src/developer_opts.c
  src/dfu.c
  src/doc/avrdude.texi
  src/jtag3.c
  src/libavrdude.h
  src/main.c
  src/micronucleus.c
  src/pickit2.c
  src/strutil.c
  src/usb_libusb.c
  src/usbasp.c
  src/usbtiny.c
Labels: enhancement

#1869 Refine programmer/part/memory compatibility for ALL expansion
  src/avr.c
  src/avrcache.c
  src/avrdude.conf.in
  src/avrpart.c
  src/disasm.c
  src/dryrun.c
  src/libavrdude.h
  src/main.c
  src/stk500v2.c
  src/term.c
  src/update.c
Labels: enhancement

#1870 Writing BOOTROW for Curiosity Nano
  src/avrcache.c
  src/jtag3.c
Labels: enhancement

#1873 Initialise dryrun flash with realistic random code
  src/avr_opcodes.c
  src/avrdude.1
  src/doc/avrdude.texi
  src/dryrun.c
  src/libavrdude.h
Labels: enhancement

#1875 Deprecate obsolete features and options
  src/avr.c
  src/avrdude.conf.in
  src/avrdude.h
  src/config_gram.y
  src/doc/avrdude.texi
  src/lexer.l
  src/main.c
  src/usbasp.c
Labels: enhancement

#1876 Add more hard-coded usbvid/pid to udev rules
  src/developer_opts.c
  src/jtag3.c
  src/usbasp.c
Labels: enhancement

#1714 SWIG Python wrapper for libavrdude
  .github/workflows/build.yml
  CMakeLists.txt
  README.md
  build.sh
  src/CMakeLists.txt
  src/avr.c
  src/avrdude.h
  src/libavrdude.h
  src/libavrdude.i
  src/main.c
  src/pgm.c
  src/python/about.ui
  src/python/adgui.bat.in
  src/python/adgui.py
  src/python/adgui.sh.in
  src/python/adgui.ui
  src/python/askfuse.ui
  src/python/device.ui
  src/python/devinfo.ui
  src/python/help.ui
  src/python/loglevel.ui
  src/python/memories.ui
  src/python/programmer.ui
  src/python/swigtest.py
Labels: enhancement

#1863 PICkit 5 support
  src/CMakeLists.txt
  src/Makefile.am
  src/avrdude.conf.in
  src/doc/avrdude.texi
  src/main.c
  src/pgm_type.c
  src/pickit5.c
  src/pickit5.h
  src/pickit5_lut.h
  src/pickit5_updi_lut.c
  src/usbdevs.h
  tools/scripts_decoder.py
Labels: enhancement

#1880 Make usbproduct available to programmers
  src/libavrdude.h
  src/stk500v2.c
  src/usb_hidapi.c
  src/usb_libusb.c
Labels: enhancement

#1883 Silently skip erasing read-only parts of a memory
  src/term.c
Labels: enhancement

#1886 Fix ATmega1284/P readsize
  src/avrdude.conf.in
Labels: bug

#1887 Fix addresses for jtag3_pdi boot and apptable
  src/jtag3.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/libavrdude.h
  src/stk500v2.c
Labels: bug

#1892 Improve documentation
  avrdude.pdf
  src/avrdude.1
  src/doc/avrdude.texi
  src/usb_hidapi.c
  src/usb_libusb.c
Labels: documentation

#1891 Some bugfixes for the tools/test-avrdude script
  .github/workflows/build.yml
  tools/test-avrdude
Labels: bug

#1902 Document: use macOS to replace MacOS, no support of Parallel Port under macOS
  src/doc/avrdude.texi
Labels: documentation

#1896 Fix deprecated types in libavrdude.i
  src/libavrdude.i
Labels: enhancement

#1901 Update build.yml to re-enable Windows on ARM64 MSVC build
  .github/workflows/build.yml
Labels: enhancement

#1903 Add -e exe option to test8
  tools/test8
Labels: enhancement

#1897 Fix avr_write_byte()
  src/avr.c
Labels: bug

#1874 Parport build test
  .github/workflows/build.yml
  CMakeLists.txt
  src/CMakeLists.txt
  src/Makefile.am
  src/configure.ac
  src/ppiwin.c
Labels: enhancement
