Repository avrdudes/avrdude, pull requests merged in 2024-03, with the labels that each got.

#1727 Replace msg_info() by msg_debug() in jtag3_prmsg() and jtag3_prevent()
  src/jtag3.c
Labels: bug

#1730 Remove unused avrdude_message()
  src/avrdude.h
  src/main.c
Labels: enhancement

#1724 Document progress reporting in source code
  src/avr.c
  src/term.c
Labels: documentation, enhancement
