Repository avrdudes/avrdude, pull requests merged in 2024-02, with the labels that each got.

#1651 Create test-avrdude's temporary files in the script itself
  tools/test-avrdude
Labels: enhancement

#1658 Update test script
  tools/test-avrdude
Labels: bug

#1659 Preliminary fix for #1655
  src/serialupdi.c
Labels: bug

#1662 Read the signature on -c jtag2updi exit if last op was write/erase
  src/jtagmkII.c
  src/libavrdude.h
  src/main.c
Labels: bug, enhancement

#1663 Automatically determine Autoconf package version from cmake package version
  .gitignore
  src/GNUmakefile.in
  src/Makefile.am
  src/build-helpers/package-version
  src/build-helpers/package-version.mk
  src/configure.ac
  src/doc/Makefile.am
Labels: enhancement

#1667 Add more programmer descriptions
  src/avrdude.conf.in
Labels: documentation

#1668 The test(1) string comparison uses =, not ==
  src/configure.ac
Labels: bug

#1686 Make avrintel.h an internal header file for libavrdude
  src/CMakeLists.txt
  src/Makefile.am
  src/avrintel.c
  src/libavrdude-avrintel.h
  src/libavrdude.h
  src/urclock_private.h
Labels: bug

#1680 Fix -Wcalloc-transposed-args warning
  src/avrftdi.c
Labels: bug

#1689 Updated section about NVM models support
  src/doc/avrdude.texi
Labels: documentation

#1699 Change port array in PROGRAMMER to be const char *
  src/CMakeLists.txt
  src/Makefile.am
  src/arduino.c
  src/avr910.c
  src/buspirate.c
  src/butterfly.c
  src/developer_opts.c
  src/ft245r.c
  src/jtag3.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/libavrdude.h
  src/linuxspi.c
  src/serialadapter.c
  src/serialupdi.c
  src/stk500.c
  src/stk500v2.c
  src/strutil.c
  src/urclock.c
  src/wiring.c
  src/xbee.c
Labels: enhancement

#1700 Fix reporting of too short r/w times for files with holes
  src/avr.c
Labels: bug

#1702 Allow slash in part variant name for `-p`
  src/main.c
Labels: bug

#1703 Abbreviate ids of modern AVR parts
  src/avrdude.conf.in
Labels: enhancement

#1709 Add benchmark option `-b` for `test-avrdude`
  tools/test-avrdude
  tools/test_files/generate_test_hex.sh
Labels: enhancement
