Repository avrdudes/avrdude, pull requests merged in 2024-07, with the labels that each got.

#1830 Add developer options /vcr to explore software compatibility of parts
  src/developer_opts.c
Labels: enhancement

#1836 Improve chip erase emulation for dryboot/dryrun
  src/avrcache.c
  src/avrdude.1
  src/doc/avrdude.texi
  src/dryrun.c
  src/term.c
Labels: enhancement

#1837 Use page erase for UPDI programming
  src/avrdude.1
  src/doc/avrdude.texi
  src/main.c
Labels: bug, enhancement

#1829 Add fuses, calibration, sernum and tempsense memories to XMEGAs
  src/avr.c
  src/avrdude.1
  src/avrdude.conf.in
  src/avrftdi.c
  src/avrpart.c
  src/butterfly.c
  src/config_gram.y
  src/developer_opts.c
  src/doc/avrdude.texi
  src/dryrun.c
  src/fileio.c
  src/jtag3.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/libavrdude.h
  src/stk500.c
  src/stk500v2.c
  src/term.c
Labels: enhancement

#1835 Alternative fix proposal for #1832
  src/serialupdi.c
  src/updi_nvm.c
  src/updi_nvm.h
  src/updi_nvm_v0.c
  src/updi_nvm_v0.h
  src/updi_nvm_v2.c
  src/updi_nvm_v2.h
  src/updi_nvm_v3.c
  src/updi_nvm_v3.h
  src/updi_nvm_v4.c
  src/updi_nvm_v4.h
  src/updi_nvm_v5.c
  src/updi_nvm_v5.h
Labels: bug

#1840 Improve signature check for UPDI parts
  src/avrpart.c
  src/config_gram.y
  src/dryrun.c
  src/fileio.c
  src/libavrdude.h
  src/main.c
  src/strutil.c
  src/update.c
Labels: bug

#1843 Improve error handling when Avrdude is built without libserialport
  src/main.c
Labels: enhancement

#1844 Extended parameters (`-x` and `-E`) improvements
  src/arduino.c
  src/avr910.c
  src/avrdude.1
  src/avrftdi.c
  src/buspirate.c
  src/butterfly.c
  src/doc/avrdude.texi
  src/dryrun.c
  src/flip2.c
  src/ft245r.c
  src/jtag3.c
  src/jtagmkII.c
  src/linuxspi.c
  src/main.c
  src/micronucleus.c
  src/par.c
  src/pickit2.c
  src/serialupdi.c
  src/serprog.c
  src/stk500.c
  src/stk500.h
  src/stk500v2.c
  src/teensy.c
  src/urclock.c
  src/usbasp.c
  src/usbtiny.c
  src/wiring.c
  src/xbee.c
Labels: enhancement
