Repository avrdudes/avrdude, pull requests merged in 2025-02, with the labels that each got.

#1945 Fix GitHub upload artifact
  .github/workflows/arduino_packing.yml
  .github/workflows/arduino_packing_release.yml
  .github/workflows/build.yml
Labels: bug

#1935 PK5 ISP, dW, TPI, JTAG and theoretical PDI support
  src/CMakeLists.txt
  src/Makefile.am
  src/avrdude.1
  src/avrdude.conf.in
  src/doc/avrdude.texi
  src/pgm_type.c
  src/pickit5.c
  src/pickit5_lut.h
  src/pickit5_lut_dw.c
  src/pickit5_lut_isp.c
  src/pickit5_lut_jtag.c
  src/pickit5_lut_pdi.c
  src/pickit5_lut_tpi.c
  src/pickit5_lut_updi.c
  src/pickit5_updi_lut.c
  tools/scripts_decoder.py
Labels: enhancement

#1939 Ensure part is up for some 100 ms before resetting it
  src/linuxspi.c
Labels: bug

#1941 Fix missing stdlib.h include for free()
  src/avrdude.h
Labels: bug

#1936 Add long options like --part
  src/avrdude.1
  src/doc/avrdude.texi
  src/main.c
Labels: enhancement

#1948 Add docs and release badges to README
  README.md
Labels: documentation

#1949 Correct PICkit5 programmer type entries
  src/avrdude.conf.in
  src/pgm_type.c
Labels: bug
