Repository avrdudes/avrdude, pull requests merged in 2025-03, with the labels that each got.

#1947 Suggest compatible command when SNAP/PICKit4 in PIC mode is detected
  src/jtag3.c
  src/pickit5.c
Labels: enhancement

#1958 Fix variant errors introduced in recent .atdf versions
  src/avrdude.conf.in
Labels: bug

#1962 Add --version option
  src/avrdude.1
  src/doc/avrdude.texi
  src/main.c
Labels: enhancement

#1964 Remove spurious s from AVR32SDnn part id
  src/avrdude.conf.in
Labels: non-technical
