Repository avrdudes/avrdude, pull requests merged in 2025-05, with the labels that each got.

#1966 PICkit Basic Documentation
  src/avrdude.conf.in
  src/doc/avrdude.texi
  src/jtag3.c
  src/pickit5.c
Labels: documentation

#1971 Remove progbuf since no longer needed
  src/avrdude.h
  src/ft245r.c
  src/jtag3.c
  src/libavrdude.i
  src/main.c
  src/update.c
Labels: bug

#1975 Alias PICkit Basic programmer names
  src/avrdude.conf.in
Labels: enhancement

#1976 adding possibility to keep supplying power with PK4/5 after exit
  src/avrdude.1
  src/doc/avrdude.texi
  src/pickit5.c
  src/pickit5_lut_dw.c
  src/pickit5_lut_isp.c
  src/pickit5_lut_jtag.c
  src/pickit5_lut_pdi.c
  src/pickit5_lut_tpi.c
  src/pickit5_lut_updi.c
  tools/scripts_decoder.py
Labels: enhancement

#1977 Set DEFAULT_SPI_PORT
  src/CMakeLists.txt
  src/avrdude.1
  src/configure.ac
  src/doc/avrdude.texi
  src/libavrdude.h
  src/linuxspi.c
  src/par.c
Labels: bug

#1981 Add `HAS_BITCLOCK_ADJ`
  src/arduino.c
  src/avr910.c
  src/avrdude.conf.in
  src/avrftdi.c
  src/bitbang.c
  src/buspirate.c
  src/butterfly.c
  src/ch341a.c
  src/config.c
  src/developer_opts.c
  src/dryrun.c
  src/flip1.c
  src/flip2.c
  src/ft245r.c
  src/jtag3.c
  src/jtagmkI.c
  src/jtagmkII.c
  src/lexer.l
  src/libavrdude.h
  src/linuxgpio.c
  src/micronucleus.c
  src/par.c
  src/pickit2.c
  src/pickit5.c
  src/serbb_posix.c
  src/serbb_win32.c
  src/serialupdi.c
  src/serprog.c
  src/stk500.c
  src/stk500v2.c
  src/teensy.c
  src/urclock.c
  src/usbasp.c
  src/usbtiny.c
  src/wiring.c
  src/xbee.c
Labels: enhancement

#1983 Retrigger `ser_posix.c` `ser_recv()` timeout
  src/ser_posix.c
Labels: bug

#1987 Fix r/w timeout for Windows `ser_send()`
  src/ser_win32.c
Labels: bug

#1992 Prevent (most) output of >= in Windows
  src/pickit5.c
  src/stk500v2.c
  src/term.c
  src/usbasp.c
Labels: misc
